import { Option, SectorPresidencyMap, SectorMap } from '../Types';

export const projectsHome = [
    {
        id: 1,
        title: "Project Alpha",
        scope: "Initial Development",
        status: "pending".toLowerCase(),
        progress: 10,
        contract_no: "A-001",
        initiation_start_date: "2023-01-05",
        initiation_end_date: "2023-03-15",
        deadline: "150",
    },
    {
        id: 2,
        title: "Project Beta",
        scope: "Research & Planning",
        status: "in progress".toLowerCase(),
        progress: 0,
        contract_no: "B-002",
        initiation_start_date: "2023-02-01",
        initiation_end_date: "2023-04-01",
        deadline: "90",
    },
    {
        id: 3,
        title: "Project Gamma",
        scope: "UI/UX Design",
        status: "todo".toLowerCase(),
        progress: 45,
        contract_no: "C-003",
        initiation_start_date: "2023-03-20",
        initiation_end_date: "2023-05-30",
        deadline: "120",
    },
    {
        id: 4,
        title: "Project Delta",
        scope: "Backend Integration",
        status: "done".toLowerCase(),
        progress: 30,
        contract_no: "D-004",
        initiation_start_date: "2023-04-10",
        initiation_end_date: "2023-06-10",
        deadline: "60",
    },
    {
        id: 5,
        title: "Project Epsilon",
        scope: "Frontend Development",
        status: "Todo".toLowerCase(),
        progress: 0,
        contract_no: "E-005",
        initiation_start_date: "2023-05-01",
        initiation_end_date: "2023-07-01",
        deadline: "90",
    },
    {
        id: 6,
        title: "Project Zeta",
        scope: "Testing Phase",
        status: "Done".toLowerCase(),
        progress: 100,
        contract_no: "Z-006",
        initiation_start_date: "2023-02-01",
        initiation_end_date: "2023-04-10",
        deadline: "0",
    },
    {
        id: 7,
        title: "Project Eta",
        scope: "Deployment Preparation",
        status: "Pending",
        progress: 0,
        contract_no: "E-007",
        initiation_start_date: "2023-07-01",
        initiation_end_date: "2023-08-20",
        deadline: "50".toLowerCase(),
    },
    {
        id: 8,
        title: "Project Theta",
        scope: "Market Research",
        status: "In Progress".toLowerCase(),
        progress: 20,
        contract_no: "T-008",
        initiation_start_date: "2023-06-01",
        initiation_end_date: "2023-07-15",
        deadline: "45",
    },
    {
        id: 9,
        title: "Project Iota",
        scope: "Feature Enhancement",
        status: "done".toLowerCase(),
        progress: 35,
        contract_no: "I-009",
        initiation_start_date: "2023-05-10",
        initiation_end_date: "2023-07-20",
        deadline: "60",
    },
    {
        id: 10,
        title: "Project Kappa",
        scope: "Testing & QA",
        status: "Todo".toLowerCase(),
        progress: 0,
        contract_no: "K-010",
        initiation_start_date: "2023-08-01",
        initiation_end_date: "2023-09-30",
        deadline: "90",
    },
    {
        id: 11,
        title: "Project Lambda",
        scope: "Documentation",
        status: "In Progress".toLowerCase(),
        progress: 50,
        contract_no: "L-011",
        initiation_start_date: "2023-07-15",
        initiation_end_date: "2023-09-01",
        deadline: "30",
    },
    {
        id: 12,
        title: "Project Mu",
        scope: "Security Updates",
        status: "Pending".toLowerCase(),
        progress: 0,
        contract_no: "M-012",
        initiation_start_date: "2023-09-05",
        initiation_end_date: "2023-11-15",
        deadline: "70",
    },
    {
        id: 13,
        title: "Project Nu",
        scope: "Database Optimization",
        status: "Done".toLowerCase(),
        progress: 100,
        contract_no: "N-013",
        initiation_start_date: "2023-04-01",
        initiation_end_date: "2023-05-25",
        deadline: "0",
    },
    {
        id: 14,
        title: "Project Xi",
        scope: "API Development",
        status: "done".toLowerCase(),
        progress: 40,
        contract_no: "X-014",
        initiation_start_date: "2023-06-20",
        initiation_end_date: "2023-08-10",
        deadline: "50",
    },
    {
        id: 15,
        title: "Project Omicron",
        scope: "System Upgrade",
        status: "In Progress".toLowerCase(),
        progress: 25,
        contract_no: "O-015",
        initiation_start_date: "2023-05-20",
        initiation_end_date: "2023-08-20",
        deadline: "30",
    },
    {
        id: 16,
        title: "Project Pi",
        scope: "Feature Planning",
        status: "Todo".toLowerCase(),
        progress: 0,
        contract_no: "P-016",
        initiation_start_date: "2023-10-01",
        initiation_end_date: "2023-11-01",
        deadline: "100",
    },
    {
        id: 17,
        title: "Project Rho",
        scope: "Cloud Integration",
        status: "Pending".toLowerCase(),
        progress: 0,
        contract_no: "R-017",
        initiation_start_date: "2023-08-01",
        initiation_end_date: "2023-09-10",
        deadline: "80",
    },
    {
        id: 18,
        title: "Project Sigma",
        scope: "Performance Analysis",
        status: "done".toLowerCase(),
        progress: 70,
        contract_no: "S-018",
        initiation_start_date: "2023-03-15",
        initiation_end_date: "2023-06-15",
        deadline: "20",
    },
    {
        id: 19,
        title: "Project Tau",
        scope: "Mobile App Development",
        status: "Done".toLowerCase(),
        progress: 100,
        contract_no: "T-019",
        initiation_start_date: "2023-05-01",
        initiation_end_date: "2023-07-30",
        deadline: "0",
    },
    {
        id: 20,
        title: "Project Upsilon",
        scope: "User Research",
        status: "In Progress".toLowerCase(),
        progress: 60,
        contract_no: "U-020",
        initiation_start_date: "2023-04-15",
        initiation_end_date: "2023-08-10",
        deadline: "15",
    }
];

export const initialProjectInfo = {
    contractor: "",
    project_manager: "",
    operating_manager: "",
    mmg: "",
    title: "",
    contract_no: "",
    scope: "",
    district: "",
    prosecution: "",
    sector_presidency: "",
    sector: "",
    contractor_name: "",
    initiation_start_date: "",
    initiation_end_date: "",
    worksite_type: "",
}

export const locations = [
    { label: "Cairo", value: "cairo" },
    { label: "Giza", value: "giza" },
    { label: "Alexandria", value: "alexandria" },
    { label: "Dakahlia", value: "dakahlia" },
    { label: "Red Sea", value: "red_sea" },
    { label: "Beheira", value: "beheira" },
    { label: "Fayoum", value: "fayoum" },
    { label: "Gharbiya 1", value: "gharbiya_1" },
    { label: "Gharbiya 2", value: "gharbiya_2" },
    { label: "Ismailia", value: "ismailia" },
    { label: "Menofia", value: "menofia" },
    { label: "Minya", value: "minya" },
    { label: "Qaliubiya", value: "qaliubiya" },
    { label: "New Valley", value: "new_valley" },
    { label: "Suez", value: "suez" },
    { label: "Aswan", value: "aswan" },
    { label: "Assiut", value: "assiut" },
    { label: "Beni Suef", value: "beni_suef" },
    { label: "Port Said", value: "port_said" },
    { label: "Damietta", value: "damietta" },
    { label: "Sharkia", value: "sharkia" },
    { label: "South Sinai", value: "south_sinai" },
    { label: "Kafr Al Sheikh", value: "kafr_al_sheikh" },
    { label: "Matrouh", value: "matrouh" },
    { label: "Luxor", value: "luxor" },
    { label: "Qena", value: "qena" },
    { label: "North Sinai", value: "north_sinai" },
    { label: "Sohag", value: "sohag" }
];

export const prosecutionOptions: Option[] = [
    { value: 'cto', label: 'CTO' },
    { value: 'vp_regional_affairs', label: 'VP Regional Affairs' }
];

export const sectorPresidencyMap: SectorPresidencyMap = {
    cto: [
    { value: 'SENIOR_director_of_tx_projects', label: 'SENIOR Director of TX Projects' },
    { value: 'SENIOR_director_of_tx_om', label: 'SENIOR Director of TX O&M' }
    ],
    vp_regional_affairs: [
    { value: 'SENIOR_director_of_projects', label: 'SENIOR Director of Projects' },
    { value: 'SENIOR_director_of_cairo', label: 'SENIOR Director of Cairo' },
    { value: 'SENIOR_director_of_west_delta', label: 'SENIOR Director of West Delta' },
    { value: 'SENIOR_director_of_east_delta', label: 'SENIOR Director of East Delta' },
    { value: 'SENIOR_director_of_upper_egypt', label: 'SENIOR Director of Upper Egypt' }
    ]
};

export const sectorMap: SectorMap = {
    SENIOR_director_of_tx_projects: [
    { value: 'director_of_tx_system_projects', label: 'Director of TX System Projects' },
    { value: 'director_of_tx_cabling_projects', label: 'Director of TX Cabling Projects' }
    ],
    SENIOR_director_of_tx_om: [
    { value: 'director_of_cairo_tx_cabling_om', label: 'Director of Cairo TX Cabling O&M' },
    { value: 'director_of_alexandria_tx_cabling_om', label: 'Director of Alexandria TX Cabling O&M' },
    { value: 'director_of_upper_egypt_tx_cabling_om', label: 'Director of Upper Egypt TX Cabling O&M' }
    ],
    SENIOR_director_of_projects: [
    { value: 'director_of_west_delta_osp_projects', label: 'Director of West Delta OSP Projects' },
    { value: 'director_of_east_delta_osp_projects', label: 'Director of East Delta OSP Projects' },
    { value: 'director_of_upper_egypt_osp_projects', label: 'Director of Upper Egypt OSP Projects' }
    ],
    SENIOR_director_of_cairo: [
    { value: 'director_of_west_cairo', label: 'Director of West Cairo' },
    { value: 'director_of_east_cairo', label: 'Director of East Cairo' },
    { value: 'director_of_new_cairo', label: 'Director of New Cairo' }
    ],
    SENIOR_director_of_west_delta: [
    { value: 'director_of_middle_delta', label: 'Director of Middle Delta' },
    { value: 'director_of_west_delta', label: 'Director of West Delta' },
    { value: 'director_of_alexandria', label: 'Director of Alexandria' },
    { value: 'director_of_north_coast', label: 'Director of North Coast' }
    ],
    SENIOR_director_of_east_delta: [
    { value: 'director_of_east_delta_1', label: 'Director of East Delta 1' },
    { value: 'director_of_east_delta_2', label: 'Director of East Delta 2' },
    { value: 'director_of_ismaillia', label: 'Director of Ismaillia' },
    { value: 'director_of_suez', label: 'Director of Suez' }
    ],
    SENIOR_director_of_upper_egypt: [
    { value: 'director_of_north_upper', label: 'Director of North Upper' },
    { value: 'director_of_south_upper', label: 'Director of South Upper' },
    { value: 'director_of_middle_upper', label: 'Director of Middle Upper' }
    ]
};

export const sectors = [
    { id: 1, name: 'director_of_alexandria' },
    { id: 2, name: 'director_of_alexandria_tx_cabling_om' },
    { id: 3, name: 'director_of_cairo_osp_projects' },
    { id: 4, name: 'director_of_cairo_tx_cabling_om' },
    { id: 5, name: 'director_of_east_cairo' },
    { id: 6, name: 'director_of_east_delta_1' },
    { id: 7, name: 'director_of_east_delta_2' },
    { id: 8, name: 'director_of_east_delta_osp_projects' },
    { id: 9, name: 'director_of_giza' },
    { id: 10, name: 'director_of_ismaillia' },
    { id: 11, name: 'director_of_middle_delta' },
    { id: 12, name: 'director_of_middle_upper' },
    { id: 13, name: 'director_of_new_cairo' },
    { id: 14, name: 'director_of_north_coast' },
    { id: 15, name: 'director_of_north_upper' },
    { id: 16, name: 'director_of_october' },
    { id: 17, name: 'director_of_south_upper' },
    { id: 18, name: 'director_of_suez' },
    { id: 19, name: 'director_of_tx_cabling_projects' },
    { id: 20, name: 'director_of_tx_system_projects' },
    { id: 21, name: 'director_of_upper_egypt_osp_projects' },
    { id: 22, name: 'director_of_upper_egypt_tx_cabling_om' },
    { id: 23, name: 'director_of_west_cairo' },
    { id: 24, name: 'director_of_west_delta' },
    { id: 25, name: 'director_of_west_delta_osp_projects' }
];

export const SectorPresidency = [
    { id: 1, name: 'SENIOR_director_of_cairo' },
    { id: 2, name: 'SENIOR_director_of_east_delta' },
    { id: 3, name: 'SENIOdirector_of_projects' },
    { id: 4, name: 'SENIOR_director_of_tx_om' },
    { id: 5, name: 'SENIOR_director_of_tx_projects' },
    { id: 6, name: 'SENIOR_director_of_upper_egypt' },
    { id: 7, name: 'SENIOR_director_of_west_delta' }
];
